"""Lineup-level DFS field modeling primitives."""

__version__ = "0.3.0"

from .baselines import compare_to_null, ownership_weighted_null
from .calibration import (
    MixtureWeightFit,
    SharedMenuCalibrationResult,
    calibrate_shared_menu,
    fit_mixture_weights,
)
from .contest import (
    ContestField,
    contest_from_draftkings,
    contest_from_long,
    contest_from_wide,
    load_draftkings_csv,
    load_long_csv,
    load_wide_csv,
)
from .core import (
    Lineup,
    SharedMenuConfig,
    SlateConfig,
    WeightedChoiceConfig,
    build_shared_menu,
    centroid,
    centroid_distance,
    duplication_count,
    effective_lineups,
    generate_shared_menu,
    generate_weighted_choice,
    generate_weighted_lineups,
    is_legal_lineup,
    legal_lineup_mask,
    lineup_hhi,
    mean_jaccard,
    near_optimal_lineups,
    optimize,
    ownership,
    ownership_lift,
    ownership_source_share,
    segment_report,
    synthetic_pool,
    top_n_lineups,
    validate_pool,
)
from .diagnostics import (
    FieldComparison,
    ObservedFieldReport,
    compare_field_reports,
    observed_field_report,
)

__all__ = [
    "SharedMenuConfig",
    "Lineup",
    "SlateConfig",
    "WeightedChoiceConfig",
    "build_shared_menu",
    "centroid",
    "centroid_distance",
    "duplication_count",
    "effective_lineups",
    "generate_shared_menu",
    "generate_weighted_choice",
    "generate_weighted_lineups",
    "is_legal_lineup",
    "legal_lineup_mask",
    "lineup_hhi",
    "mean_jaccard",
    "near_optimal_lineups",
    "optimize",
    "ownership",
    "ownership_lift",
    "ownership_source_share",
    "segment_report",
    "synthetic_pool",
    "top_n_lineups",
    "validate_pool",
    "ContestField",
    "contest_from_draftkings",
    "contest_from_long",
    "contest_from_wide",
    "load_draftkings_csv",
    "load_long_csv",
    "load_wide_csv",
    "FieldComparison",
    "ObservedFieldReport",
    "compare_field_reports",
    "observed_field_report",
    "compare_to_null",
    "ownership_weighted_null",
    "MixtureWeightFit",
    "SharedMenuCalibrationResult",
    "calibrate_shared_menu",
    "fit_mixture_weights",
]
